services:
  react-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: npm run dev:docker
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./:/app
      - react_app_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - shared-network
    stdin_open: true
    tty: true

  storybook:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: npm run storybook:docker
    ports:
      - "${STORYBOOK_PORT:-6006}:6006"
    volumes:
      - ./:/app
      - storybook_node_modules:/app/node_modules
    networks:
      - shared-network


volumes:
  react_app_node_modules:
    driver: local
  storybook_node_modules:
    driver: local

networks:
  shared-network:
    driver: bridge